pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "jsandeep9866/crud-backend"
    }

    stages {

        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/17pa1a0447-tech/Backendcode.git'
            }
        }

        stage('Maven Build') {
            steps {
                dir('crud-application') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('crud-application') {
                     sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jsandeep9866',
                        usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_IMAGE}:latest
                    docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}
                    docker push ${DOCKER_IMAGE}:latest
                    docker logout
                    """
                }
            }
        }

    }

    post {
        success {
            echo "Backend Build & Push Successful"
        }
        failure {
            echo "Pipeline Failed"
        }
    }
}
